name: Build Gradle Project

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle wrapper
        id: gradle
        run: ./gradlew build

      - name: Fail on build failure
        if: ${{ steps.gradle.outputs.result != 'SUCCESS' }}
        run: |
          echo "Build failed!"
          exit 1